name:                issuefetcher
version:             0.1.0.0
github:              "githubuser/issuefetcher"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/issuefetcher#readme>

dependencies:
- base >= 4.7 && < 5
- base-compat-batteries
- text
- bytestring
- http-client
- http-client-tls
- aeson
- http-conduit
library:
  source-dirs: src

executables:
  issuefetcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - issuefetcher

tests:
  issuefetcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - issuefetcher
